### ISSUE TITLE
010-Feature-Cleaning the repository to remove dependencies on CoffeeScript, jQuery, Grunt and SCSS

### ISSUE THREAD

**Issue by rashi-bhansali** [Shyam-Sundar-Bharathi/cse210-tinyfoot-team14#14]
Since Tinyfoot is built on top of Bigfoot, after migrating the jQuery to JS ES6, the repository needs to be cleaned:
- remove dependencies on CoffeeScript, jQuery, Grunt and other related packages (update bower.json and package.json)
- remove **scss files and folders** as they've been replaced with CSS owing to the small scale of the project.
- rename our converted ES6 file (`src/js/bigfoot.js`) to `src/js/tinyfoot.js` and ensuring a standard naming convention for styles and other files
- make `index.html` _demo-ready_
- add the following to `bower.json` and `package.json` : 
  - `"name": "Tinyfoot",
  - "main": "src/js/tinfoot.js",
  - "version": "<>",
  - "hosted at": "<>",
  - "authors": [ "<name> <<email>>", ...],
  - "description": "<>",`

**Comment by MitchelHsu** [comment]
@rashi-bhansali few questions:
> make index.html demo-ready

What does demo-ready mean?

> add the following to bower.json and package.json

I think we can remove `bower.json` and only keep `package.json`, since they serve the same purpose? can correct me if I'm wrong.

**Comment by rashi-bhansali** [comment]
> @rashi-bhansali few questions:
> 
> > make index.html demo-ready
> 
> What does demo-ready mean?
> 
> > add the following to bower.json and package.json
> 
> I think we can remove `bower.json` and only keep `package.json`, since they serve the same purpose? can correct me if I'm wrong.

- Demo ready means we want to remove the current date, news, etc. and instead provide three buttons - Default, Numeric, and Bottom (the way it shows on [by](https://bigfootjs.com/)
- bower.json is used when it’s just client side (like in our case) but package.json is more ubiquitous cause it has hierarchical dependencies which are good for client and server both. 
To answer your question - yes, we can have one of them.

**Comment by rashi-bhansali** [comment]
We need to remove the changelog, license and readme-dev files from Bigfoot.

**Comment by MitchelHsu** [comment]
Do we need to update the changelog or remove it

**Comment by rashi-bhansali** [comment]
> Do we need to update the changelog or remove it

I think we can make it empty for now and update it later.
